corrected scripts

diff --git a/scripts/capture b/scripts/capture
--- a/scripts/capture
+++ b/scripts/capture
@@ -11,10 +11,10 @@ DEF_POINTS_PER_LEVEL=5 # For the "stops" exposure plan
 DEF_MAX_DN=4095 # For the "stops" exposure plan
 DEF_TAG="flat"
 DEF_GAIN=1
-DEF_EXPOSURE_PLAN="combi"
+DEF_EXPOSURE_PLAN="combistops"
 
 
-read -p "Exposure plan (linear|log|combi|stops) [$DEF_EXPOSURE_PLAN]: " exposure_plan
+read -p "Exposure plan (linear|log|stops|combilog|combistops) [$DEF_EXPOSURE_PLAN]: " exposure_plan
 exposure_plan=${exposure_plan:-$DEF_EXPOSURE_PLAN}
 read -p "Start Exposure time (us) Tinitial: " tinitial
 read -p "End Exposure time (us): Tfinal: " tfinal
@@ -38,27 +38,34 @@ then
 	reverse=${reverse:-$DEF_REVERSE}
 	if [[ "$reverse" = "y" ]]; then reverse="-r" ; else reverse=""; fi
 	echo "gonet-exposure --log-file ${DEF_LOG_FILE} log -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -n ${npoints} ${reverse}"
-	exposure_times=$(gonet-exposure --log-file ${DEF_LOG_FILE} linear -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -n ${npoints} ${reverse})
-elif [[ "$exposure_plan" = "combi" ]]
+	exposure_times=$(gonet-exposure --log-file ${DEF_LOG_FILE} log -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -n ${npoints} ${reverse})
+elif [[ "$exposure_plan" = "combilog" ]]
 then
-	read -p "Lower cut-off exposure time (${tinitial} < Tco < Tc1 < ${tfinal})  Tc0 (us): " tc0
-	read -p "Upper cut-off exposure time (${tinitial} < ${tco} < Tc1 < ${tfinal}) Tc1 (us): " tc1
 	read -p "Number of images to take [$DEF_NPOINTS]: " npoints
 	npoints=${npoints:-$DEF_NPOINTS}
-	read -p "Reverse exposure plan (y/n) [$DEF_REVERSE]: " reverse
-	reverse=${reverse:-$DEF_REVERSE}
-	if [[ "$reverse" = "y" ]]; then reverse="-r" ; else reverse=""; fi
-	exposure_times=$(gonet-exposure --log-file ${DEF_LOG_FILE} combi -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -tc0 ${tc0}/1000000 -tc1 ${tc1}/1000000 -n ${npoints} ${reverse})
-else
+	echo "gonet-exposure --log-file ${DEF_LOG_FILE} log -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -n ${npoints}"
+	exposure_times=$(gonet-exposure --log-file ${DEF_LOG_FILE} combilog -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -n ${npoints})
+elif [[ "$exposure_plan" = "stops" ]]
+then
 	read -p "Number of images per level to take [$DEF_POINTS_PER_LEVEL]: " ppl
 	ppl=${ppl:-$DEF_POINTS_PER_LEVEL}
-	read -p "Saturation value (y/n) [$DEF_MAX_DN]: " max_dn
+	read -p "Saturation value [$DEF_MAX_DN]: " max_dn
 	max_dn=${max_dn:-$DEF_MAX_DN}
 	read -p "Reverse exposure plan (y/n) [$DEF_REVERSE]: " reverse
 	reverse=${reverse:-$DEF_REVERSE}
 	if [[ "$reverse" = "y" ]]; then reverse="-r" ; else reverse=""; fi
 	echo "gonet-exposure --log-file ${DEF_LOG_FILE} stops -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -m ${max_dn} -ppl ${ppl} ${reverse}"
-	exposure_times=$(gonet-exposure --log-file ${DEF_LOG_FILE} combi -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -m ${max_dn} -ppl ${ppl} ${reverse})
+	exposure_times=$(gonet-exposure --log-file ${DEF_LOG_FILE} stops -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -m ${max_dn} -ppl ${ppl} ${reverse})
+elif [[ "$exposure_plan" = "combistops" ]]
+then
+	read -p "Number of images per level to take [$DEF_POINTS_PER_LEVEL]: " ppl
+	ppl=${ppl:-$DEF_POINTS_PER_LEVEL}
+	read -p "Saturation value [$DEF_MAX_DN]: " max_dn
+	max_dn=${max_dn:-$DEF_MAX_DN}
+	echo "gonet-exposure --log-file ${DEF_LOG_FILE} stops -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -m ${max_dn} -ppl ${ppl}"
+	exposure_times=$(gonet-exposure --log-file ${DEF_LOG_FILE} combistops -ti ${tinitial}/1000000 -tf ${tfinal}/1000000 -m ${max_dn} -ppl ${ppl})
+else
+	echo "ERROR. Exposure plan ${exposure_plan} not supported"
 fi
 
 for i_t in ${exposure_times}
@@ -67,9 +74,9 @@ do
 	t=${i_t:4:7}
 	image=${tag}_g${analog_gain}_${i}_${t}_a.jpg
 	echo "raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image}"
-	raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image} || exit 255
+	#raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image} || exit 255
 
 	image=${tag}_g${analog_gain}_${i}_${t}_b.jpg
 	echo "raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image}"
-	raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image} || exit 255
+	#raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image} || exit 255
 done  
